### ISSUE TITLE
pry on this lesson doesn't work

### ISSUE THREAD

**Issue by swarbrick85** [learn-co-curriculum/anagram-detector#16]
Anagram Detector

**Comment by drakeltheryuujin** [comment]
hi @swarbrick85,

Can you provide more context on what you're trying to do? If you're having trouble solving the lab,  would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks!

**Comment by maxwellbenton** [comment]
Hi @swarbrick85,

Thank you for bringing this issue to our attention. I've added a gemfile and updated this lessons support files to make sure that pry is now working.

Thank you for contributing to a learn.co lesson!
